/**
 * Per-downstream tool allowlist for the A2A MCP proxy (Spec 007 Phase E).
 *
 * The generic `/mcp/:server/:tool` route used to forward any tool name a
 * client supplied, regardless of whether the A2A surface intended to
 * expose that tool. This file is the source-of-truth contract for what
 * tools are reachable through the proxy.
 *
 * Adding a new tool to a downstream MCP DOES NOT automatically expose it
 * through the proxy — the operator must also add the tool name to the
 * matching set below, and that addition is reviewed in PRs. Removing a
 * tool from the allowlist closes the surface IMMEDIATELY (kill-switch
 * granularity is per-tool, not per-MCP).
 *
 * The sets enumerate exactly the tools the downstream MCP exposes today.
 * Mirror updates to a downstream MCP's `src/tools/` listing into the
 * matching set below; the unit test `proxy-tool-allowlist.test.ts`
 * asserts no unknown tool is forwarded.
 *
 * NOTE: `hub` does NOT appear in this map — the `/mcp/hub/:tool` route
 * is a dedicated system-level gateway with its own MAC envelope and
 * different argument shape (no delegation token, no session binding).
 * It performs its own validation against the hub-mcp tool registry on
 * receipt.
 */

/** Person-mcp `/tools/<name>` — see `apps/person-mcp/src/tools/`. */
export const PERSON_TOOLS = new Set<string>([
  'add_external_identity',
  'add_message',
  'add_oikos_contact',
  'create_notification',
  'create_thread',
  'create_work_item',
  'delete_belief',
  'delete_coaching_note',
  'delete_oikos_contact',
  'delete_prayer',
  'express_intent',
  'get_delegated_profile',
  'get_delegated_training_progress',
  'get_intent',
  'get_profile',
  'get_shared_coaching_notes',
  'get_thread',
  'get_user_preferences',
  'grant_cross_delegation',
  'grant_proposal:clone',
  'grant_proposal:draft',
  'grant_proposal:edit_pre_deadline',
  'grant_proposal:list_for_member',
  'grant_proposal:read_self',
  'grant_proposal:submit',
  'grant_proposal:withdraw',
  'intent:bump_ack_count',
  'list_activities',
  'list_beliefs',
  'list_coaching_notes',
  'list_cross_delegation_grants',
  'list_external_identities',
  'list_intents',
  'list_notifications',
  'list_oikos_contacts',
  'list_pinned_items',
  'list_prayers',
  'list_received_delegations',
  'list_threads',
  'list_training_progress',
  'list_work_items',
  'log_activity',
  'mark_notification_read',
  'mark_prayer_response',
  'pin_item',
  'register_received_delegation',
  'relationship:emit_edge',
  'relationship:list_outgoing',
  'relationship:set_edge_status',
  'remove_external_identity',
  'resolve_work_item',
  'revoke_cross_delegation',
  'revoke_received_delegation',
  'ssi_create_presentation',
  'ssi_create_wallet_action',
  'ssi_finish_credential_exchange',
  'ssi_get_credential_details',
  'ssi_get_holder_wallet',
  'ssi_get_marketplace_delegation',
  'ssi_list_my_credentials',
  'ssi_list_proof_audit',
  'ssi_list_wallets',
  'ssi_match_against_public_set',
  'ssi_provision_wallet',
  'ssi_rotate_link_secret',
  'ssi_start_credential_exchange',
  'toggle_planned_conversation',
  'toggle_training_module',
  'unpin_item',
  'update_oikos_contact',
  'update_profile',
  'update_user_preferences',
  'upsert_belief',
  'upsert_coaching_note',
  'upsert_prayer',
  'withdraw_intent',
])

/** Org-mcp `/tools/<name>` — see `apps/org-mcp/src/tools/`. */
export const ORG_TOOLS = new Set<string>([
  'add_detached_member',
  'add_policy_signer',
  'agent:deploy',
  'agent_resolver:add_multi_address_property',
  'agent_resolver:read',
  'agent_resolver:read_address_property',
  'agent_resolver:register',
  'agent_resolver:set_address_property',
  'agent_resolver:set_string_property',
  'approve_revenue_report',
  'attach_engagement_policy',
  'attestation:cast',
  'attestation:list_for_proposal',
  'commitment:cancel',
  'commitment:commit',
  'commitment:get',
  'commitment:list',
  'commitment:record_outcome',
  'commitment:record_release',
  'create_org_notification',
  'create_org_work_item',
  'delete_detached_member',
  'disbursement:claim',
  'disbursement:list_for_proposal',
  'disbursement:list_for_recipient',
  'disbursement:mark_paid',
  'disbursement:record',
  'express_org_intent',
  'fund_registry:get_round_fund_agent',
  'fund_registry:get_round_status',
  'fund_registry:list_rounds_by_pool',
  'get_org_profile_private',
  'grant_proposal:award',
  'grant_proposal:clone',
  'grant_proposal:count_for_round',
  'grant_proposal:draft',
  'grant_proposal:edit_pre_deadline',
  'grant_proposal:list_for_member',
  'grant_proposal:list_for_round',
  'grant_proposal:read_self',
  'grant_proposal:rescind',
  'grant_proposal:revoke_award',
  'grant_proposal:submit',
  'grant_proposal:withdraw',
  'init_engagement_provider_state',
  'intent:bump_ack_count',
  'list_detached_members',
  'list_engagement_sessions',
  'list_org_activities',
  'list_org_beliefs',
  'list_org_intents',
  'list_org_notifications',
  'list_org_outcomes',
  'list_org_work_items',
  'list_revenue_reports',
  'log_org_activity',
  'mark_org_notification_read',
  'match_initiation:consume',
  'match_initiation:create',
  'match_initiation:read',
  'match_initiation:supersede',
  'pool:close',
  'pool:create',
  'pool:rotate_stewards',
  'pool:set_accepted_restrictions',
  'pool:update_mandate',
  'pool_pledge:amend',
  'pool_pledge:auto_stop',
  'pool_pledge:list_for_pool',
  'pool_pledge:read_pool_counters',
  'pool_pledge:read_self',
  'pool_pledge:stop',
  'pool_pledge:submit',
  'pool_registry:get_pool',
  'pool_registry:list_pools_by_steward',
  'proposal_registry:announce_award',
  'proposal_registry:set_status',
  'proposal_submitter_cred:issue',
  'proposal_submitter_cred:revoke',
  'reject_revenue_report',
  'release_engagement_tranche',
  'resolve_org_work_item',
  'round:cancel',
  'round:close',
  'round:get_voting_config',
  'round:increment_proposals_received',
  'round:open',
  'round:set_awards_root',
  'round:set_status',
  'round:update_voting_config',
  'round_voter_cred:issue',
  'round_voter_cred:revoke',
  'schedule_engagement_session',
  'schedule_engagement_tranche',
  'submit_revenue_report',
  'update_org_profile_private',
  'upsert_org_belief',
  'vote:cast',
  'vote:list_for_proposal',
  'vote:list_for_round',
  'vote:list_for_voter',
  'vote:tally_for_round',
  'withdraw_org_intent',
])

/** People-group-mcp `/tools/<name>` — see `apps/people-group-mcp/src/tools/`. */
export const PEOPLE_GROUP_TOOLS = new Set<string>([
  'add_classification',
  'add_estimate',
  'add_geometry',
  'add_reachedness_assessment',
  'delete_community',
  'get_pg_concept',
  'get_segment',
  'list_audit_log',
  'list_classification_schemes',
  'list_communities',
  'list_estimates_for_segment',
  'list_external_records',
  'list_geometries',
  'list_pg_collectives',
  'list_pg_concepts',
  'list_reachedness_for_segment',
  'list_scope_types',
  'list_segments',
  'register_classification_scheme',
  'register_external_record',
  'register_pg_collective',
  'register_pg_concept',
  'revoke_pg_delegation',
  'upsert_community',
  'upsert_segment',
])

/** Hub-mcp tool registry — exposed by the dedicated `/mcp/hub/:tool` route. */
export const HUB_TOOLS = new Set<string>([
  'debug:agents_turtle',
  'discovery:count_agents_by_type',
  'discovery:count_edges',
  'discovery:get_agent_detail',
  'discovery:get_hop_distance',
  'discovery:get_incoming_edges',
  'discovery:get_outgoing_edges',
  'discovery:get_pool_detail',
  'discovery:get_round_detail',
  'discovery:list_active_initiations_for_intent',
  'discovery:list_agents',
  'discovery:list_candidates_for_intent',
  'discovery:list_pools',
  'discovery:list_recent_allocations',
  'discovery:list_rounds',
  'discovery:raw_sparql',
  'sync:all',
  'sync:all_commitments',
  'sync:all_pools',
  'sync:pool',
  'sync:round',
  'sync:schedule',
])

/** Map server key → allowed tool set for the generic `/mcp/:server/:tool` proxy. */
export const SERVER_TOOL_ALLOWLIST: Record<string, Set<string>> = {
  person: PERSON_TOOLS,
  org: ORG_TOOLS,
  'people-group': PEOPLE_GROUP_TOOLS,
}
